# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

#language: R
#sudo: false
#cache: packages
#r_build_args: --resave-data --compact-vignettes=gs+qpdf
#r_check_args: --resave-data --compact-vignettes=gs+qpdf
#script: 
#  - |
#    travis_wait 30 R CMD build .
#    travis_wait 30 R CMD check ctsem*tar.gz
#after_failure:
#- find *Rcheck -name '*.fail' -print -exec cat '{}' \;



--- 
after_failure: 
  - "./pkg-build.sh dump_logs"
before_install: 
  - "curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh"
  - "chmod 755 pkg-build.sh"
  - "./pkg-build.sh bootstrap"
env: 
  matrix: 
    - RVERSION=devel
    - RVERSION=release
install: 
  - "travis_wait 30 ./pkg-build.sh install_deps"
language: c
notifications: 
  email: 
    on_failure: change
    on_success: change
script: 
  - "travis_wait 60 ./pkg-build.sh run_tests"
sudo: required

