# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_build_args: --resave-data --compact-vignettes=gs+qpdf
r_check_args: --resave-data --compact-vignettes=gs+qpdf
script: 
  - |
    rm ctsem*tar.gz
    travis_wait 30 R CMD build .
    travis_wait 30 R CMD check ctsem*tar.gz
after_failure:
- find *Rcheck -name '*.fail' -print -exec cat '{}' \;
