# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

#language: R
#sudo: false
#cache: packages
#r_build_args: --resave-data --compact-vignettes=gs+qpdf
#r_check_args: --resave-data --compact-vignettes=gs+qpdf
#script: 
#  - |
#    travis_wait 30 R CMD build .
#    travis_wait 30 R CMD check ctsem*tar.gz
#after_failure:
#- find *Rcheck -name '*.fail' -print -exec cat '{}' \;




language: r
cache: packages
latex: true
r_build_args: --resave-data --compact-vignettes=gs+qpdf
r_check_args: --resave-data --compact-vignettes=gs+qpdf
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
#- sudo tlmgr install framed

matrix:
  include:
    - os: linux
      sudo: required
      r: release
    - os: linux
      sudo: required
      r: devel
    - os: osx
      sudo: required
      disable_homebrew: true



script: 
  - |
    travis_wait 30 R CMD build .
    travis_wait 30 R CMD check ctsem*tar.gz

notifications:
  email:
    on_success: change
on_failure: change

