# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

#language: R
#sudo: false
#cache: packages
#r_build_args: --resave-data --compact-vignettes=gs+qpdf
#r_check_args: --resave-data --compact-vignettes=gs+qpdf
#script: 
#  - |
#    travis_wait 30 R CMD build .
#    travis_wait 30 R CMD check ctsem*tar.gz
#after_failure:
#- find *Rcheck -name '*.fail' -print -exec cat '{}' \;




language: r
cache: packages
dist: trusty
latex: true
sudo: required
r_build_args: --resave-data --compact-vignettes=gs+qpdf
r_check_args: --resave-data --compact-vignettes=gs+qpdf

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      osx_image: xcode8.3


script: 
  - |
    travis_wait 30 R CMD build .
    travis_wait 30 R CMD check ctsem*tar.g

notifications:
  email:
    on_success: change
on_failure: change

